name: Create Pull Request
on:
  push:
    branches:
      - 'release/*'
      - main
      - dev

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ github.ref }}
          base: main
          title: "Release: ${{ github.ref }}"
          body: "This is an automated pull request for release branch ${{ github.ref }}."
          labels: release
