name: Create Feature/Fix/Hotfix Branch

permissions:
  contents: write # for pushing the code back to your desired branch
  
on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
      
      - name: Determine Branch Type and Create Branch
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          BRANCH_TYPE=$(echo "$COMMIT_MSG" | awk '{print tolower($1)}')
          BRANCH_NAME=$(echo "$COMMIT_MSG" | sed 's/[^a-zA-Z0-9]/-/g' | awk '{print tolower($0)}')
          NEW_BRANCH="${BRANCH_TYPE}/${BRANCH_NAME}-${{ github.sha }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
