name: Create Feature Branch

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new branch
        run: |
          BRANCH_TYPE=${{ github.event.head_commit.message }}
          NEW_BRANCH="${BRANCH_TYPE}/${{ github.sha }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
