name: Hotfix Branch Workflow

on:
  push:
    branches:
      - 'hotfix/**'
      - 'feature/**'
      - 'fix/**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm test

  merge:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Merge push branch into main
        run: |
          git checkout main
          git merge --no-ff ${{ github.ref }}
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Merge push branch into dev
        run: |
          git checkout dev
          git merge --no-ff ${{ github.ref }}
          git push origin dev
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
