name: Create Feature/Fix/Hotfix Branch

on:
  push:
    branches:
      - 'main'
      - 'development'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Determine Branch Type and Create Branch
        run: |
          BRANCH_TYPE=$(echo "${{ github.event.head_commit.message }}" | awk '{print tolower($1)}')
          NEW_BRANCH="${BRANCH_TYPE}/${{ github.sha }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH
