name: Merge PR to Testing Branch

permissions:
  contents: write # for pushing the code back to your desired branch
  pull-requests: write # Add this optional for allowing the action to make a comment of acknowledgment on the PR

on:
  push:
    branches:
      - main
      - dev
      - staging
      
  pull_request:
    branches:
      - master
      - main
      - dev
      - staging
    types:
      - opened
      - reopened
      - synchronize
  release:
    types: [published]
jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checks out code
      uses: actions/checkout@v3

    - name: Merge PR to Testing Branch
      uses: solenova-tech/gamma@v1.3.1 # replace version with latest from https://github.com/marketplace/actions/gamma-ci-made-easy
      with:
        target-branch: 'dev' # replace this name with your testing branch

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        
