name: Auto Merge PR

on:
  push:
    branches:
      - main
      - master
      - dev
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      
  pull_request:
    types: [closed]

jobs:
  merge_pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge PR into main branch
      if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
      run: |
        git fetch origin
        git checkout main
        git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"

    - name: Merge PR into dev branch
      if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
      run: |
        git fetch origin
        git checkout dev
        git merge --no-ff ${{ github.event.pull_request.head.ref }} -m "Merge pull request #${{ github.event.pull_request.number }}"

  create_release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create release branch
      run: |
        # Extract branch name
        BRANCH_NAME=$(echo $GITHUB_REF | cut -d '/' -f 2)
        git checkout -b release/$BRANCH_NAME

    - name: Create PR for release
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        title: "Release PR: ${{ github.event.head_ref }}"
        labels: 'release'
        body: "Automatically generated PR for upcoming release."
        branch: "release/${{ github.event.head_ref }}"
